spring:
  application:
    name: event-ingestion
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
camelshop:
    rabbitmq:
        exchange: eventingestion.exchange
        queue: eventingestion.queue
        routingKey: camelshop.#