spring:
  application:
    name: event-ingestion
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
camelshop:
  datasource:
    url: jdbc:sqlite:camelshop.db
  rabbitmq:
    exchange: eventingestion.exchange
    queue: eventingestion.queue
    routingKey: camelshop.#