spring:
  application:
    name: event-routing
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration
camelshop:
  event-routing:
    input-directory: event-routing/data/input
    processed-directory: event-routing/data/processed
    error-directory: event-routing/data/error
  rabbitmq:
    exchange: eventrouting.exchange
    queue: eventrouting.queue
    routingKey: camelshop.#